# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9c99f775eea31f26572e8cfad8750efa4dff184a232c69dd5bf9fcfa840cea23589f74aa3c8d4235ab86657251d2793adfb118308a1594f1824d1ee2901fdbfd

test:
  secret_key_base: 141ac2e66101f599002a5f189d1934ac52059a98c228bfd196bc91c80ab7c867da0db05bd88d4218df80630e3e888dc3956f7716ea993e66b05d3db6c8e77c92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
